services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: link-postgres
    environment:
      POSTGRES_USER: linkuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: link-db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
